/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#2d3449",
        "inverse-surface": "#dae2fd",
        "on-surface-variant": "#c3c5d9",
        "tertiary-container": "#006e95",
        "background": "#0b1326",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "on-primary-fixed": "#001452",
        "on-tertiary": "#00354a",
        "primary": "#b7c4ff",
        "surface": "#0b1326",
        "surface-container-high": "#222a3d",
        "on-secondary": "#472a00",
        "outline": "#8d90a2",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-background": "#dae2fd",
        "primary-fixed": "#dde1ff",
        "surface-tint": "#b7c4ff",
        "inverse-primary": "#004ced",
        "tertiary-fixed": "#c4e7ff",
        "on-error": "#690005",
        "on-primary-container": "#dfe3ff",
        "secondary": "#ffb95f",
        "on-surface": "#dae2fd",
        "on-primary": "#002682",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed-variant": "#0038b6",
        "surface-dim": "#0b1326",
        "surface-container": "#171f33",
        "on-tertiary-container": "#caeaff",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed-variant": "#653e00",
        "secondary-fixed": "#ffddb8",
        "outline-variant": "#434656",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "tertiary": "#7bd0ff",
        "error-container": "#93000a",
        "on-secondary-fixed": "#2a1700",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "secondary-container": "#ee9800",
        "on-secondary-container": "#5b3800",
        "on-error-container": "#ffdad6",
        "primary-container": "#0052ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "16px",
        "xl": "64px",
        "lg": "40px",
        "md": "24px",
        "base": "4px",
        "xs": "8px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "headline-md": ["Sora"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Sora"],
        "display-lg": ["Sora"],
        "label-sm": ["Sora"],
        "code-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "code-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
